### PR TITLE
Add Brazilian Portuguese translation

### PR DESCRIPTION
**Pull request by marcelocg**
Closes: #67

### CODE REVIEW

**Review by LombardiDaniel — COMMENTED** [review]
@marcelocg I'm already doing the transaltions, around 1/3 of the way there, feel free to contribute! take a look at [my fork](https://github.com/LombardiDaniel/system-design-101)!

- Já estou traduzindo, estou com cerca de 1/3 do documento traduzido! Sinta-se a vontade para dar uma olhada e contribuir

**Comment by marcelocg** [comment]
Ok, @LombardiDaniel thanks for the heads up. But you should have done a PR as soon as you started in order to make it easy for everyone to collaborate. Well, you can do it now and then we can help each other.

**Comment by LombardiDaniel** [comment]
Sure thing! will open it now

**Comment by LombardiDaniel** [comment]
Take a look at #71 , I created it as a draft for now

**Comment by marcelocg** [comment]
Even better @LombardiDaniel you can add your commits to this very PR to avoid cluttering the repo or annoying people.

**Comment by LombardiDaniel** [comment]
Its better if you contribute in my PR since i already translated more pages, you can just close this PR.

**Comment by marcelocg** [comment]
I live in Portugal, but I am brazilian 😎🇧🇷😃

**Comment by LombardiDaniel** [comment]
@marcelocg  I'm actually quite new to contributing to open source projects, so if there are any heads up i need to know so we can work together, please tell me. Since we have terms in portuese for common english ones, I somethimes keep both portuguese and english wordings on the docs, like this: `CDN (Rede de distribuição de Conteúdos, _Content Delivery Network_)`, please keep this pattern in the translations as it is important for ppl to make the connection

**Pull request closed without merging**
