### PR TITLE
Fixed Typo: 'RIFGH JOIN' should be 'RIGHT JOIN' #12

### PR DESCRIPTION
**Pull request by UsmanLiaqat404**

### CODE REVIEW

**Review by susanhsrestha — CHANGES_REQUESTED** [review]
The image is cropped out. Can you fix this?

**Comment by UsmanLiaqat404** [comment]
@susanhsrestha yes i can

**Comment by UsmanLiaqat404** [comment]
@susanhsrestha please verify changes

**Review by susanhsrestha — CHANGES_REQUESTED** [review]
The font at different places is different. Can you use constant font for all items in the image?

**Comment by UsmanLiaqat404** [comment]
in orignal [image](https://github.com/ByteByteGoHq/system-design-101/blob/main/images/how-to-learn-sql.jpg) fonts are different i just fixes the typo mistake if you want i can same the all fonts

**Comment by susanhsrestha** [comment]
Do you know the font of original image?

**Comment by UsmanLiaqat404** [comment]
yes

**Comment by susanhsrestha** [comment]
Yes, you can use that. I guess the original image only contains that font with different font sizes.

**Comment by UsmanLiaqat404** [comment]
i see clearly now that there is no difference in font just feel difference because of some are in uppercase and some are in lower case characters

**Comment by susanhsrestha** [comment]
I see. You can use constant spacing and font and push the changes.

**Comment by slam** [comment]
Thank you for taking the time to contribute. The tool you used to fix this image unfortunately introduced some artifacts that lowered the overall image quality. We went ahead and fixed the typo ourselves to avoid those artifacts. We appreciate you bringing this to our attention.

**Pull request closed without merging**
